### ISSUE TITLE
Can this be made to work in asset editor?

### ISSUE THREAD

**Issue by wgwine** [Craxy/ToggleTrafficLights#17]
I would like to manage traffic lights for saved intersections.

**Comment by Craxy** [comment]
Unfortunately no: I could enable the tool in the assets editor, BUT mods cannot save data for assets (unlike savegames). 
Ergo: you could  use TTL in the assets editor -- but the Lights wouldn't be saved into the asset and therefore wouldn't shown up with their desired states in game.

thus: sorry -- but in the way I store the Lights it's not possible.

**Comment by wgwine** [comment]
:( oh well. Thanks for responding.
