### ISSUE TITLE
Underground traffic lights.

### ISSUE THREAD

**Issue by CSJoJo** [Craxy/ToggleTrafficLights#18]
Hey

f you find some time somewhere, can you maybe add so we can change the light on underground traffic lights. whit the tunnels added, it would be rly nice :D ive tried but cant find a way to click the underground ones. maybe just add kinda the same function we have on roads know, when we push pagedown we get to see the underground instead of the surface.

**Comment by Craxy** [comment]
Will definitely add that.
But as I stated in the Comments on the Workshop pages, I have currently no spare time -- so it might take a while, sorry :(
