### ISSUE TITLE
Options aren't saved (correctly?)

### ISSUE THREAD

**Issue by WillFa** [Craxy/ToggleTrafficLights#32]
Haven't tried changing colors, but if you change the drop down for "intersections to highlight" from Underground to All, exit the game, and come back, it's not remembered.

**Comment by Craxy** [comment]
They are not saved at all -- it's just not implemented yet: https://github.com/Craxy/ToggleTrafficLights/releases/tag/0.9.0
And for some reasons I haven't done it yet....

So: "Options aren't saved" is unfortunately correct behavior.....It's not a bug -- it's a missing feature!....
But I leave this issue open -- I should definitely implement saving and this issue reminds me ;)

**Comment by Craxy** [comment]
Options get now saved (33c2b86)
