### ISSUE TITLE
Mod stopped working/ Buttons are gone

### ISSUE THREAD

**Issue by PalamonIV** [Craxy/ToggleTrafficLights#37]
Hey, I have a problem with your Mod. Its really great, but it caused a bug, and now the whole mod doesnt work anymore. 
1. I bought Afterdark and Snowfall
2. I installed your mod
3. I played a savegame from before i bought the DLC´s and installed your mod
4. At first it was fine, but suddenly there were no more hearse, they didnt come out of their buildings and noone picked up the dead ones
5. I started a new map, same problem here
6. I restarted the game, the problem was gone but the mod stopped working. The complete "options" button in the mod menu is gone, and also the ingame button for your mod disappeared

Several restarts didnt solve the problem. Also repairing and reinstalling didnt fix it. Can you help me?
Thanks

**Comment by PalamonIV** [comment]
Problem solved. Somehow  the button appeared somewhere else. Maybe Steam installed a wrong version.

**Comment by Craxy** [comment]
Can you post a screenshot with the button? And best your `output_log.txt` (in `Cities_Skylines\Cities_Data`) too?

Wrong version shouldn't be the case -- steam is pretty good at fetching the newest version. But even if it's an older version: the really early version had no buttons at all, and in the first versions with a button it was placed just a couple pixel right of its current position. So an old version should either show no button at all or just a slightly indented button.
My guess: an other mod changes your UI, but doesn't know about TTL and therefore handles the button somewhat strange. Can you try TTL without any other mods activated?

**Comment by PalamonIV** [comment]
Its all fine, thanks. There was another button, which wasnt part of your mod, but it also changed traffic lights so i thought it was. My fault, sorry.

**Comment by Craxy** [comment]
That's most likely one of the Traffic Manager mods, which has that ability (amongst a lot other -- really a great mod if you want to micromanage your traffic).

However: I'm glad it wasn't an issue of TTL
